export const AUTHORIZE_USER = 'AUTHORIZE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR';
export const GET_SIDEBAR_ITEMS = 'GET_SIDEBAR_ITEMS';
export const GET_MENU_STATE = 'GET_MENU_STATE';

